### ISSUE TITLE
Log Me In's button sometimes appears after a noticeable lag, during which the browser gets frozen

### ISSUE THREAD

**Issue by Drugoy** [sarahavilov/logmein#4]
Log Me In's button sometimes appears after a noticeable lag, during which the browser becomes unresponsive.
After the Log Me In's button appears - the lags are gone, the interface is not frozen anymore.
Could you add an option to use an always visible toolbar button instead?
I switched from Secure Login to Log Me In only because it's restartless and I irrationally like restartless add-ons.

**Comment by sarahavilov** [comment]
Log Me In's startup performance should be much better than SL. Can you confirm this on a clean profile?
http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

As a side note, SDK based addon's are loaded after Firefox is being fully initialized, so if the button is not there when you start your Firefox is okay, but there should be no unresponsiveness due to this add-on.

This is what I get from about:performance. You need Firefox developer for this:
![screen shot 2016-06-08 at 09 52 01](https://cloud.githubusercontent.com/assets/12985412/15883660/7ad3e69c-2d5f-11e6-9b3e-ac6eeb903a06.png)

**Comment by sarahavilov** [comment]
I have pushed a new version that may have affect on the performance in your case. Please give https://github.com/sarahavilov/logmein/blob/master/src/jid1-Ptzss5HIFsnISg@jetpack-0.2.0b1.xpi?raw=true a try and let me know how it performs.

You need to download the XPI then open about:debugging and load the XPI

**Comment by Drugoy** [comment]
> Log Me In's startup performance should be much better than SL.

I was not talking about a browser startup performance, but about browser getting frozen when I open some site where I'm logged off but that I have saved logins for.
Also, those lags are semi random: sometimes they don't happen at all, sometimes they are causing freezes of up to 5 sec duration.

> This is what I get from about:performance. You need Firefox developer for this

It's already available on release versions as well.
Here's a screenshot of what I get with Log Me In when visiting a site where I'm logged off (though there was no freeze this time):
<img src="https://i.imgur.com/lI7gbdr.png">

I'm still seeing alerts on about:performance cause by log me in with the beta, but since yesterday when I disabled TreeStyleTab add-on (which for me turned out to be the main cause of firefox performance (lags, freezes, especially when new tab is getting opened or Firefox window gets resized)) - I am unable to reproduce freezes of log me in - although I get spikes of CPU usage on (as shown on about:performance tab) up to 81% - it still doesn't result into UI freezes, as it used to.

So hold on for some time - I'll try to test for a few days/weeks and see if the issue is completely gone after disabling TST or not.

**Comment by sarahavilov** [comment]
Have you tried the dev version? There should be no spikes in the CPU usage at all. Not at least at this rate; 85%. If you still observe these spikes let me know the site address.

**Comment by Drugoy** [comment]
Yes, I did. I still experience the spikes and getting alerts by this add-on, but the CPU usage is now usually around 32% (49% was the maximum that I've noticed). That's still kinda high, since even on sites where I'm logged in - Log Me In is usually a #1 CPU consumer and opening any page causes Log Me In to consume ~20% CPU per 1 tab load and generates an alert.
By loading 4-6 tabs in ~8 sec I was able to make Log Me In reach 86% CPU consumption.
:(

**Comment by sarahavilov** [comment]
the new dev version does not calculate anything when a new tab is loaded. It just installs a listener to perform all the calculations once the tab is visible. I am not sure how the CPU usage can reach to 86% with just this minimal execution.

Anyhow please play around with the dev version and let me know if there is any freezing.

**Comment by Haven667** [comment]
Hi Sarah,

I can confirm the CPU intensive problem. I tested **Log Me In** against **Secure Login**. Sadly **Secure Login** seems to be more lightweight (at the moment) for me.

What I've done: Started my regular session with many (unloaded) tabs and logged in in 8 sites with **Log Me In**. Then took the screenshot, deleted all forms, cookies, history, cache, etc. and quitted Firefox. The same procedure with **Secure Login**.

This is what the **about:performance** measured:

![logmein](https://cloud.githubusercontent.com/assets/9346225/16550715/92ab338e-41ae-11e6-912c-4d23bfd13ba8.jpg)

![securelogin](https://cloud.githubusercontent.com/assets/9346225/16550717/95f3d078-41ae-11e6-88dc-da79f9b2a7e3.jpg)

Tested with Firefox v47, **Log Me In v0.2.0** and **Secure Login v1.2.1**.

Greetings

**Comment by sarahavilov** [comment]
@AtTheGates please give 0.2.1 a try and let me know how it performs
https://addons.mozilla.org/en-US/firefox/addon/log-me-in/versions/

**Comment by Haven667** [comment]
This is what I got with **v0.2.1** after starting the session and logging in in my 8 sites:

![logmein_0 2 1_1](https://cloud.githubusercontent.com/assets/9346225/16552247/c92327f8-41bf-11e6-90e6-46da2983a774.png)

And here the browser was idle for a longer time:

![logmein_0 2 1_2](https://cloud.githubusercontent.com/assets/9346225/16552262/d86ab032-41bf-11e6-833c-f4b26d83e811.png)

**Comment by Haven667** [comment]
Ok, I tested it (same session) with all my other Add-ons disabled - just with **Log Me In v0.2.1**.

![log_me_in_0 2 1_3](https://cloud.githubusercontent.com/assets/9346225/16552553/3e8d7334-41c2-11e6-88e3-3368f49a369a.png)

**Comment by sarahavilov** [comment]
@AtTheGates what is your Firefox version?

**Comment by Haven667** [comment]
The first tests (vs. **Secure Login**) was Firefox v47. The last tests was with Firefox v47.0.1.

So it seems **Log Me In** has a problem with another Add-on. I will enable them one by one and let you know. Just give me time. ^^

**Comment by sarahavilov** [comment]
This seems more like a Firefox issue than Log Me In. I believe when you increase your add-ons performance of each one degraded. Let me know if you could track down a single add-on.

**Comment by Haven667** [comment]
I'm very sorry, but the last test (with just **Log Me In**) was done wrong by me. I accidentally activated the **about:performance** AFTER all tabs were loaded and I logged in in my 8 sites. So it wasn't measured correctly.

So this is the the session started with **about:performance** as active tab and with logging in in my 8 sites. **Log Me In** was the only Add-on again. And now? :-(

![log_me_in_0 2 1_4](https://cloud.githubusercontent.com/assets/9346225/16553696/587f521e-41ca-11e6-9020-440cf457626b.png)

**Comment by sarahavilov** [comment]
Can you try to perform this test with another SDK based add-on. This add-on needs to inject something into webpages and has a toolbar panel. That's it. I have checked the code one more time. Log Me In does the minimum possible background activities as I can imagine right now. There is no icon generation until page is visible or there is no password check until a page actually has a form and the form is visible. 

So I am not sure what else we can do to have a better performance. 

Also note that FF 47 has some internal performance issues that has been reported in reddit channel. You may get better performance results using dev or nightly builds.

**Comment by Haven667** [comment]
Yes, very strange. I really want to use **Log Me In** instead of **Secure Login**. If there is anything to test, let me know.

Newest test: I upgraded to Nightly (v50.0a1). A little bit better. But not as good as **Secure Login**:

![log_me_in_0 2 1_5](https://cloud.githubusercontent.com/assets/9346225/16557322/5ec73474-41df-11e6-97e4-15476e089142.png)

**Comment by sarahavilov** [comment]
At this point I am not sure how I can improve the performance further. Will keep this open for inputs or suggestions.

**Comment by Haven667** [comment]
> Can you try to perform this test with another SDK based add-on.

The SDK extension [Redirect Control v0.1.2](https://addons.mozilla.org/firefox/addon/redirect-control) has also a big performance impact for me:

![redirectcontrol_0 1 2](https://cloud.githubusercontent.com/assets/9346225/16711836/f7a55c18-466f-11e6-9f70-69ac33be17cd.png)

On the other hand the SDK extension [Load from Cache v0.0.2](https://addons.mozilla.org/firefox/addon/load-from-cache) seems to peform well:

![loadfromcache](https://cloud.githubusercontent.com/assets/9346225/16711845/5480e8b2-4670-11e6-9616-bce946054996.png)

I hope this helps in any way.

**Comment by sarahavilov** [comment]
@AtTheGates it really depends on what modules these extensions are using. LogMeIn uses "page_mod" (injecting scripts into pages) which I believe causes the performance sparks.
